version: '2.1'

services:

  fma-db:
    container_name: fma-db
    build: ./project/db
    ports:
      - 5435:5432 # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  flask-microservices-app-service:
    container_name: flask-microservices-app-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@fma-db:5432/fma_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@fma-db:5432/fma_test
    depends_on:
      fma-db:
        condition: service_healthy
    links:
      - fma-db